### PR TITLE
 Update array syntax for future rstan compatibility

### PR DESCRIPTION
**Pull request by andrjohns**
Now that rstan 2.26 is available on CRAN we need to update your package's Stan models to use the new array syntax, otherwise it will fail to install with an upcoming version of RStan. If you could merge and submit to CRAN soon, it would be greatly appreciated.

Let me know if you have any questions about these changes.

Thanks!

### CODE REVIEW

**Comment by isaacvock** [comment]
Sounds good, thank you for updating the syntax for me!

**Comment by andrjohns** [comment]
@isaacvock would it be possible to push these release to CRAN soon? Otherwise your package will break with the next rstan version

**Comment by isaacvock** [comment]
My bad, this got put on backburner but I will submit to CRAN a release with these changes this afternoon

**Comment by andrjohns** [comment]
Not a problem, much appreciated!

**Pull request merged**
